version: "3"
services:
    db:
        image: mysql:5
        restart: always
        volumes:
            - common:/var/lib/mysql
            - ./db-init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: "area"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        container_name: MYSQL_Database
        ports:
            - "3306:3306"
        expose:
            - "3306"
        networks:
            area_network:
                ipv4_address: 172.20.1.1

    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '8082:80'
        networks:
            area_network:
                ipv4_address: 172.20.1.3

    server:
        build: ./AreaApi/
        image: area
        ports:
            - '8080:8080'
        depends_on:
            - db
        volumes:
            - /app/node_modules
            - ./AreaApi:/app
        networks:
            area_network:
                ipv4_address: 172.20.1.2
    
    client_web:
        build: ./AreaWeb/
        image: web
        depends_on:
            - server
            - mobile
        ports:
            - '8081:8081'
        volumes:
            - /app/node_modules
            - ./AreaWeb:/app
            - common:/var/www:ro
        networks:
            area_network:
                ipv4_address: 172.20.1.4
    mobile:
        build: ./AreaApp/
        image: mobile
        depends_on:
            - server
            - nginx
        volumes:
            - common:/usr/src/app/build/outputs/apk/:rw

volumes:
    common:

networks:
    area_network:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16