version: "3"
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: "area"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
            ACCEPT_EULA: "Y"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - my-db:/var/lib/mysql
    server:
        build: .
        image: area
        ports:
             # - "8081:443"
            - "8080:80"
        expose:
            - "8080"
        depends_on:
            - db
    nginx:
        image: nginx:latest
        depends_on:
            - server
        ports:
            # - "8080:80"
            # - "8081:443"
        volumes:
            - /:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - /certs:/etc/nginx/certs
    web:
        image: web
        depends_on: 
        ports:
            - "8081:80"
        expose:
            - "8081"
        volumes:
            - common:/home/
    mobile:
        image: mobile
        depends_on:
        volumes:
            - common:/home/

volumes:
    common:
    my_db: