version: "3"
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            MYSQL_DATABASE: "area"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - common:/var/lib/mysql
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - '8082:80'
    api:
        build: ./AreaApi/
        image: area
        ports:
            - '8081:8081'
        depends_on:
            - db
        volumes:
            - /app/node_modules
            - ./AreaApi:/app
    web:
        build: ./AreaWeb/
        image: web
        depends_on:
            - api
            - mobile
        ports:
            - '8080:8080'
        volumes:
            - /app/node_modules
            - ./AreaWeb:/app
            - common:/var/www/:ro
    mobile:
        build: ./AreaApp/
        image: mobile
        depends_on:
            - api
            - nginx
        volumes:
            - common:/usr/src/app/build/outputs/apk/:rw

volumes:
    common: