version: "3"
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            MYSQL_DATABASE: "area"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - common:/var/lib/mysql
    server:
        build: ./AreaApi/AreaApi/
        image: area
        ports:
             # - "8081:443"
            - "8080:80"
        expose:
            - "8080"
        depends_on:
            - db
    # nginx:
        # image: nginx:latest
        # depends_on:
        #     - server
        # ports:
        #     - "8081:80"
        # volumes:
        #     - /:/var/www
        #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #     - /certs:/etc/nginx/certs
    web:
        build: ./Area/Area
        image: web
        depends_on:
            - mobile
            - server
        ports:
            - "8081:80"
        expose:
            - "8081"
        volumes:
            - common:/home/
    mobile:
        build: ./AreaApp/
        image: mobile
        depends_on:
            - server
        volumes:
            - common:/home/

volumes:
    common: