version: "3"
services:
    db:
        image: mysql:latest
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            MYSQL_DATABASE: "area"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - common:/var/lib/mysql
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
        links:
            - web
    api:
        build: ./AreaApi/AreaApi/
        image: area
        ports:
            - "8080:8080"
        depends_on:
            - db
    web:
        build: ./Area/Area
        image: web
        depends_on:
            - mobile    
            - api
        expose:
            - "8081"
        # ports:
        #     - "8082:3000"
        volumes:
            - common:/var/www/:ro
    mobile:
        build: ./AreaApp/
        image: mobile
        depends_on:
            - api
        volumes:
            - common:/usr/src/app/app/build/outputs/apk/:rw

volumes:
    common: